---
- name: Disabling The Apache Signature
  replace: >
    dest={{ security_file }}
    replace="ServerTokens Prod"
    regexp="^ServerTokens OS$"
  when: ansible_pkg_mgr == "apt"
  tags: 
    - apache

- name: Disabling The Apache Signature
  replace: >
    dest=/etc/httpd/conf/httpd.conf
    replace="ServerTokens Prod"
    regexp="^ServerTokens OS$"
  when: ansible_pkg_mgr == "yum"
  tags: 
    - apache

- name: Disabling The OS Information
  replace: >
    dest={{ security_file }}
    replace="ServerSignature Off"
    regexp="^ServerSignature On$"
  when: ansible_pkg_mgr == "apt"
  tags: 
    - apache2

- name: Disabling The OS Information
  replace: >
    dest=/etc/httpd/conf/httpd.conf
    replace="ServerSignature Off"
    regexp="^ServerSignature On$"
  when: ansible_pkg_mgr == "yum"
  tags: 
    - apache
